package com.jesuskrastev.bali.data.audio

import android.content.Context
import android.media.AudioAttributes
import android.media.SoundPool
import androidx.annotation.RawRes
import androidx.datastore.preferences.core.booleanPreferencesKey
import androidx.datastore.preferences.core.edit
import androidx.datastore.preferences.preferencesDataStore
import com.google.firebase.crashlytics.FirebaseCrashlytics
import com.jesuskrastev.bali.R
import com.jesuskrastev.bali.domain.audio.SoundEffects
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.distinctUntilChanged
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.launch
import javax.inject.Inject
import javax.inject.Singleton

private val Context.soundDataStore by preferencesDataStore(name = "sound")

/**
 * [SoundEffects] played through a [SoundPool], with the on/off choice kept in DataStore.
 *
 * DataStore rather than the user profile: it is a preference of this device, and the local
 * profile is wiped on sign-in. The effects are original recordings generated by
 * `tools/sounds/generate_sounds.py`, so there is no third-party licence to track.
 *
 * `SoundPool` loads every file once, when the singleton is first injected, and plays them over
 * whatever else the phone is playing without taking audio focus. They follow the media volume.
 */
@Singleton
class SoundPoolSoundEffects @Inject constructor(
    @ApplicationContext private val context: Context
) : SoundEffects {

    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.Default)

    private val soundPool: SoundPool = SoundPool.Builder()
        .setMaxStreams(4)
        .setAudioAttributes(
            AudioAttributes.Builder()
                .setUsage(AudioAttributes.USAGE_GAME)
                .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                .build()
        )
        .build()

    private val correctSoundId = load(R.raw.sfx_correct)
    private val wrongSoundId = load(R.raw.sfx_wrong)
    private val lessonCompleteSoundId = load(R.raw.sfx_lesson_complete)
    private val softFinishSoundId = load(R.raw.sfx_soft_finish)
    private val chestOpenSoundId = load(R.raw.sfx_chest_open)
    private val pickupSoundId = load(R.raw.sfx_pickup)
    private val powerUpSoundId = load(R.raw.sfx_powerup)
    private val sirenSoundId = load(R.raw.sfx_siren)

    override val isEnabled: Flow<Boolean> = context.soundDataStore.data
        .map { preferences -> preferences[KEY_ENABLED] ?: true }
        .distinctUntilChanged()

    /**
     * Stores [enabled], replacing the earlier choice.
     *
     * @param enabled true to play sound effects, false to keep the app silent
     */
    override suspend fun setEnabled(enabled: Boolean) {
        context.soundDataStore.edit { preferences -> preferences[KEY_ENABLED] = enabled }
    }

    override fun playCorrect() = play(correctSoundId)

    override fun playWrong() = play(wrongSoundId)

    override fun playLessonComplete() = play(lessonCompleteSoundId)

    override fun playSoftFinish() = play(softFinishSoundId)

    override fun playChestOpen() = play(chestOpenSoundId)

    override fun playPickup(pitch: Float) = play(pickupSoundId, rate = pitch.coerceIn(0.5f, 2f))

    override fun playPowerUp() = play(powerUpSoundId)

    override fun playSiren() = play(sirenSoundId)

    /**
     * Starts loading a raw sound resource into the pool. Loading is asynchronous: a sound asked
     * for before it finished loading is skipped instead of delaying the caller.
     *
     * @param resId raw resource of the sound
     * @return the pool's id for the sound, 0 when it could not be queued
     */
    private fun load(@RawRes resId: Int): Int = soundPool.load(context, resId, 1)

    /**
     * Plays [soundId] once at full volume unless the user switched sounds off. Any failure is
     * reported to Crashlytics and swallowed, so the test the sound belongs to carries on.
     *
     * @param soundId id returned by [load]
     * @param rate playback rate (0.5–2), which also shifts the pitch; 1 plays it as recorded
     */
    private fun play(soundId: Int, rate: Float = 1f) {
        scope.launch {
            try {
                if (isEnabled.first()) {
                    soundPool.play(soundId, 1f, 1f, 1, 0, rate)
                }
            } catch (e: Exception) {
                FirebaseCrashlytics.getInstance().recordException(e)
            }
        }
    }

    private companion object {
        val KEY_ENABLED = booleanPreferencesKey("sound_effects_enabled")
    }
}
