package com.jesuskrastev.bali.ui.screens.home

import com.jesuskrastev.bali.domain.model.LessonNode
import com.jesuskrastev.bali.domain.model.NodeStatus
import com.jesuskrastev.bali.domain.model.NodeType
import com.jesuskrastev.bali.domain.path.LessonQuestionBank

/**
 * Picks the path node the "Haz tu primer test" first step opens.
 *
 * The first test has to be a normal one, with the written questions of [LessonQuestionBank], never
 * one generated by Gemini. So only lessons with written questions qualify: reviews and exams are
 * skipped even when they are the next node of the path (an exam node would even open a mock exam). The next lesson to do wins; when none is unlocked (the student is on a
 * review or an exam), the last lesson already done is repeated instead.
 *
 * @param pathNodes the student's learning path, in any order.
 * @param hasWrittenQuestions tells whether a node id has questions in the bank; replaceable in tests.
 * @return the lesson to open, or null when the path has no reachable lesson with written questions.
 */
internal fun firstStepTestNodeOf(
    pathNodes: List<LessonNode>,
    hasWrittenQuestions: (String) -> Boolean = LessonQuestionBank::hasQuestionsForNode
): LessonNode? {
    val lessons = pathNodes
        .filter { it.nodeType == NodeType.LESSON && hasWrittenQuestions(it.id) }
        .sortedBy { it.orderIndex }
    return lessons.firstOrNull { it.status == NodeStatus.UNLOCKED }
        ?: lessons.lastOrNull { it.status == NodeStatus.COMPLETED }
}

/**
 * Picks the exam the first-steps bar's closing "Simulacro" button opens.
 *
 * An exam only asks about the lessons of its unit that the student has completed, so the button
 * has nothing to open until the first unit's exam is unlocked: the first simulacro cannot be
 * taken before the unit is studied.
 *
 * @param pathNodes the student's learning path, in any order.
 * @return the earliest exam node that is unlocked, or null when none is yet.
 */
internal fun firstStepExamNodeOf(pathNodes: List<LessonNode>): LessonNode? =
    pathNodes
        .filter { it.nodeType == NodeType.EXAM && it.status == NodeStatus.UNLOCKED }
        .minByOrNull { it.orderIndex }
