package com.jesuskrastev.bali.domain.path

/**
 * Static question bank for every lesson node in the DGT learning path.
 * Keys match deterministic node IDs from DgtLearningPathTemplate.
 *
 * The questions live in `question_bank/lesson_questions.json` (a Java resource packaged with the app),
 * not in code. Their pictures are hosted in Firebase Storage under `questions/`.
 */
object LessonQuestionBank {

    /**
     * Base download URL for DGT traffic sign images hosted in Firebase Storage
     * (public-read, `signs/` path). Images were re-hosted from Wikimedia Commons
     * because Coil's requests to commons.wikimedia.org were being rate-limited
     * (HTTP 429) without an identifying User-Agent, causing signs to fail to load.
     */
    private const val SIGN_IMAGE_BASE_URL =
        "https://firebasestorage.googleapis.com/v0/b/bali-ai-facc4.firebasestorage.app/o/signs%2F"

    /** Builds the public Firebase Storage download URL for a sign image PNG by file name (without extension). */
    fun signImage(fileName: String) = "${SIGN_IMAGE_BASE_URL}$fileName.png?alt=media"

    /** Builds the public Firebase Storage URL for a mini-game asset stored under `game-assets/`. */
    fun gameAsset(fileName: String) =
        "https://firebasestorage.googleapis.com/v0/b/bali-ai-facc4.firebasestorage.app/o/game-assets%2F$fileName.png?alt=media"

    /** Builds the public Firebase Storage download URL for a question picture, e.g. `3f2a….jpg`. */
    fun questionImage(fileName: String) =
        "https://firebasestorage.googleapis.com/v0/b/bali-ai-facc4.firebasestorage.app/o/questions%2F$fileName?alt=media"

    data class StaticQuestion(
        val text: String,
        val options: List<String>,
        val correctAnswerIndex: Int,
        val explanation: String,
        val imageUrl: String? = null
    )

    private const val BANK_RESOURCE = "question_bank/lesson_questions.json"

    /** Questions of every lesson node, read from [BANK_RESOURCE] the first time any of them is needed. */
    private val questionsPerNode: Map<String, List<StaticQuestion>> by lazy { loadBank() }

    /**
     * Reads and parses the bank file packaged with the app.
     *
     * @return the questions of every node, keyed by node id.
     * @throws IllegalStateException when the resource is missing, which means the app was built wrongly.
     */
    private fun loadBank(): Map<String, List<StaticQuestion>> {
        val stream = LessonQuestionBank::class.java.classLoader?.getResourceAsStream(BANK_RESOURCE)
            ?: error("Question bank resource $BANK_RESOURCE is missing")
        return stream.bufferedReader(Charsets.UTF_8).use { LessonQuestionBankParser.parse(it.readText(), ::questionImage) }
    }

    /**
     * Returns up to [count] questions for the given [nodeId], shuffled.
     *
     * @param nodeId the path node to take questions for.
     * @param count the most questions to return.
     * @return a random selection of the node's questions, or an empty list when the node has none.
     */
    fun getQuestionsForNode(nodeId: String, count: Int = 10): List<StaticQuestion> {
        val all = questionsPerNode[nodeId] ?: return emptyList()
        return all.shuffled().take(count)
    }

    /**
     * Returns every question the bank holds for [nodeId], in file order.
     *
     * Unlike [getQuestionsForNode] it neither shuffles nor cuts the list: an exam wants the whole
     * lesson to draw from, not the ten a single lesson test shows.
     *
     * @param nodeId the path node to take questions for.
     * @return all of the node's questions, or an empty list when the node has none.
     */
    fun allQuestionsForNode(nodeId: String): List<StaticQuestion> = questionsPerNode[nodeId].orEmpty()

    /**
     * Tells whether [nodeId] has written questions, i.e. whether its test loads from this bank
     * instead of being generated by Gemini.
     *
     * @param nodeId the path node to look up.
     * @return true when the bank holds at least one question for [nodeId].
     */
    fun hasQuestionsForNode(nodeId: String): Boolean = !questionsPerNode[nodeId].isNullOrEmpty()
}
